version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - tuskboard_db
  tuskboard_db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=tuskboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    volumes:
      - tuskboard_postgres_data:/var/lib/postgresql/data/

volumes:
  tuskboard_postgres_data: